#!/bin/bash

! . ~/.bash_funcs && echo '** Critical error (bash_funcs).' >&2 && exit 1

this_dir=${BASH_SOURCE%/*}
libname=${BASH_SOURCE##*update-}

gitrepo=$libname
[[ $gitrepo == mcbkt-client ]] && gitrepo=client-mcbkt

src_dir="$(git-cd -n $gitrepo)"
jsfile=$libname.js

! [[ -d $src_dir ]] && echo '** No git source folder for '$jsfile'.' >&2 && \
	exit 2

src_file="$src_dir/dist/$jsfile"
tgt_file="$this_dir/../src/js-ext/$jsfile"

make -C "$src_dir" && cp -a "$src_file" "$tgt_file"
