#!/bin/bash

! . ~/.bash_funcs && echo '** Critical error (bash_funcs).' >&2 && exit 1

this_dir=${BASH_SOURCE%/*}

iframe_dir="$(git-cd -n _iframe)"

! [[ -d $iframe_dir ]] && echo '** No iframe git source folder.' >&2 && \
	exit 2

src_file="$iframe_dir/dist/iframe-phone.js"
tgt_file="$this_dir/../src/js/iframe-phone.js"

pushd $iframe_dir 1>/dev/null

pull_msg=$(git pull 2>&1)
[[ $pull_msg != "Already up-to-date." ]] && {
	npm install
	npm run build
}

popd 1>/dev/null

cp -a "$src_file" "$tgt_file"
