stages:
  - build
  - deploy

stg:
  type: build
  script:
    - sudo ~gitlab-runner/scr/dispatch stg
  only:
    - master

pro:
  type: deploy
  script:
    - sudo ~gitlab-runner/scr/dispatch pro
  only:
    - /release$/
  except:
    - branches
